<?php
/*******************************************************************************************
*   ___  _          ______                     _ _                _                        *
*  / _ \| |         | ___ \                   | (_)              | |              © 2020   *
* / /_\ | | _____  _| |_/ /_ __ __ _ _ __   __| |_ _ __   __ _   | |_ ___  __ _ _ __ ___   *
* |  _  | |/ _ \ \/ / ___ \ '__/ _` | '_ \ / _` | | '_ \ / _` |  | __/ _ \/ _` | '_ ` _ \  *
* | | | | |  __/>  <| |_/ / | | (_| | | | | (_| | | | | | (_| |  | ||  __/ (_| | | | | | | *
* \_| |_/_|\___/_/\_\____/|_|  \__,_|_| |_|\__,_|_|_| |_|\__, |  \___\___|\__,_|_| |_| |_| *
*                                                         __/ |                            *
*                                                        |___/                             *
* ---------------------------------------------------------------------------------------- *
* This is commercial software, only users who have purchased a valid license and accept    *
* to the terms of the License Agreement can install and use this program.                  *
* ---------------------------------------------------------------------------------------- *
* website: https://cs-cart.alexbranding.com                                                *
*   email: info@alexbranding.com                                                           *
*******************************************************************************************/
use Tygh\Registry;if (!defined('BOOTSTRAP')) {
die('Access denied');}
if ($_SERVER[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'U0ZSVkZUVWBORlVJUEU='))] == call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'UVBUVQ=='))) {
return;}
if (call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'XVV6aGldU2ZoanR1c3o7O2hmdQ==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'c3ZvdWpuZi9ucGVm'))) == call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'dnFlYnVm'))) {
$static_data=Tygh::$app['view']->getTemplateVars(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'dHVidWpkYGVidWI=')));if (!empty($static_data[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'YmNgYGdvYG5mb3ZgdHVidXZ0'))]) && $static_data[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'YmNgYGdvYG5mb3ZgdHVidXZ0'))] == call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'Wg=='))) {
$s_data=call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'ZWNgaGZ1YHNweA==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'VEZNRkRVIWJjYGBnb2BtYmNmbWB1Znl1LSFiY2BgZ29gbWJjZm1gdGlweCFHU1BOIUA7dHVidWpkYGVidWJgZWZ0ZHNqcXVqcG90IVhJRlNGIW1ib2hgZHBlZiE+IUB0IUJPRSFxYnNibmBqZSE+IUBq')),DESCR_SL,$_REQUEST[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'cWJzYm5gamU='))]);$static_data=call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'YnNzYnpgbmZzaGY=')),$static_data,$s_data);$static_data[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'YmNgYGdvYG5mb3ZgamRwbw=='))]=call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'Z29gaGZ1YGpuYmhmYHFianN0')),$_REQUEST[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'cWJzYm5gamU='))],call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'YmNgYGdvYG5mb3ZgamRwbw==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'Tg==')),true,false);Tygh::$app['view']->assign(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49bc`11:d49````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'009c38','',ab_____('11:d49cbtf7511:d49`efdpef')),'dHVidWpkYGVidWI=')),$static_data);}}
